### PR TITLE
Add additional worker nodes

### PR DESCRIPTION
**Pull request by ivan-georgiev-zetta**
Raising the workers in Publish and Delivery Staging and Production clusters. More information in:
https://trello.com/c/0ZQJfBnw/812-find-do-we-meet-the-resource-requirements-in-terms-of-cluster-capacity
https://trello.com/c/mNkDfbt9/549-evaluate-ebs-sizes-after-deciding-on-our-retention-period
CPH-17
UPPSF-249

### CODE REVIEW

**Review by mihaylovmihail — DISMISSED** [review]
It seems fine for me.

**Comment by tamas-molnar** [comment]
Will this be done in dev too?

**Comment by ivan-georgiev-zetta** [comment]
I have to analyze the metrics to see if there is resource shortage for dev too.

**Comment by tamas-molnar** [comment]
The clusters should be identical, so dev should be the same as staging and prod.

**Comment by mihaylovmihail** [comment]
@tamas-molnar Could you please check and verify last changes of @ivan-georgiev-zetta ?

**Review by emilangelov — APPROVED** [review]
Looks good, but lets do costs estimations too.

**Pull request merged**
